const postActionTypes = {
  LIKE_POST: 'LIKE_POST',
  ADD_NEW_COMMENT: 'ADD_NEW_COMMENT',
  LIKE_POST: 'LIKE_POST',
  FETCH_ALL_POSTS_AND_COMMENTS_START: 'FETCH_ALL_POSTS_AND_COMMENTS_START',
  FETCH_ALL_POSTS_AND_COMMENTS_SUCCESS: 'FETCH_ALL_POSTS_AND_COMMENTS_SUCCESS',
  FETCH_ALL_POSTS_AND_COMMENTS_FAILURE: 'FETCH_ALL_POSTS_AND_COMMENTS_FAILURE',
  FETCH_COMMENTS_FOR_USER_START: 'FETCH_COMMENTS_FOR_USER_START',
  FETCH_COMMENTS_FOR_USER_SUCCESS: 'FETCH_COMMENTS_FOR_USER_SUCCESS',
  FETCH_COMMENTS_FOR_USER_FAILURE: 'FETCH_COMMENTS_FOR_USER_FAILURE',
};

export default postActionTypes;