const userActionTypes = {
  FETCH_CURRENT_USER_ID_START: 'FETCH_CURRENT_USER_ID_START',
  FETCH_CURRENT_USER_ID_SUCCESS: 'FETCH_CURRENT_USER_ID_SUCCESS',
  FETCH_CURRENT_USER_ID_FAILURE: 'FETCH_CURRENT_USER_ID_FAILURE',
}

export default userActionTypes;